sudo: required
language: cpp
git:
    depth: 1

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

        packages:
            - g++-5
            - gcc-5
            - libfreetype6-dev
            - libjpeg-dev
            - libx11-dev
            - libxrandr-dev
            - libxcb1-dev
            - libx11-xcb-dev
            - libxcb-randr0-dev
            - libxcb-image0-dev
            - libgl1-mesa-dev
            - libflac-dev
            - libogg-dev
            - libvorbis-dev
            - libvorbisenc2
            - libvorbisfile3
            - libopenal-dev
            - libpthread-stubs0-dev
            - libglew-dev
            - libgpgme11-dev
            - libsndfile1-dev
            - libudev-dev

before_install:
    - pip install --user codecov

before_script:
    - export CXX='g++-5'
    - export CC='gcc-5'
    - ./install_deps.sh

script:
    - mkdir build
    - cd build
    - cmake .. -DTLG_BUILD_TESTS=True -DCMAKE_BUILD_TYPE=Debug
    - make
    - ./TheLostGirlTests
    - find -name "*.gcno" | xargs gcov > /dev/null

after_success:
  - bash <(curl -s https://codecov.io/bash) > /dev/null
