.TH "AutoVersion" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoVersion \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBDATE\fP [] = '01'"
.br
.ti -1c
.RI "static const char \fBMONTH\fP [] = '10'"
.br
.ti -1c
.RI "static const char \fBYEAR\fP [] = '2014'"
.br
.ti -1c
.RI "static const char \fBUBUNTU_VERSION_STYLE\fP [] = '14\&.10'"
.br
.ti -1c
.RI "static const char \fBSTATUS\fP [] = 'Prealpha'"
.br
.ti -1c
.RI "static const char \fBSTATUS_SHORT\fP [] = 'pa'"
.br
.ti -1c
.RI "static const long \fBMAJOR\fP = 0"
.br
.ti -1c
.RI "static const long \fBMINOR\fP = 0"
.br
.ti -1c
.RI "static const long \fBBUILD\fP = 7"
.br
.ti -1c
.RI "static const long \fBREVISION\fP = 0"
.br
.ti -1c
.RI "static const long \fBBUILDS_COUNT\fP = 1"
.br
.ti -1c
.RI "static const char \fBFULLVERSION_STRING\fP [] = '0\&.0\&.7\&.0'"
.br
.ti -1c
.RI "static const long \fBBUILD_HISTORY\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const long AutoVersion::BUILD = 7\fC [static]\fP"

.PP
Definition at line 19 of file version\&.h\&.
.SS "const long AutoVersion::BUILD_HISTORY = 0\fC [static]\fP"

.PP
Definition at line 29 of file version\&.h\&.
.SS "const long AutoVersion::BUILDS_COUNT = 1\fC [static]\fP"

.PP
Definition at line 23 of file version\&.h\&.
.SS "const char AutoVersion::DATE[] = '01'\fC [static]\fP"

.PP
Definition at line 7 of file version\&.h\&.
.SS "const char AutoVersion::FULLVERSION_STRING[] = '0\&.0\&.7\&.0'\fC [static]\fP"

.PP
Definition at line 26 of file version\&.h\&.
.SS "const long AutoVersion::MAJOR = 0\fC [static]\fP"

.PP
Definition at line 17 of file version\&.h\&.
.SS "const long AutoVersion::MINOR = 0\fC [static]\fP"

.PP
Definition at line 18 of file version\&.h\&.
.SS "const char AutoVersion::MONTH[] = '10'\fC [static]\fP"

.PP
Definition at line 8 of file version\&.h\&.
.SS "const long AutoVersion::REVISION = 0\fC [static]\fP"

.PP
Definition at line 20 of file version\&.h\&.
.SS "const char AutoVersion::STATUS[] = 'Prealpha'\fC [static]\fP"

.PP
Definition at line 13 of file version\&.h\&.
.SS "const char AutoVersion::STATUS_SHORT[] = 'pa'\fC [static]\fP"

.PP
Definition at line 14 of file version\&.h\&.
.SS "const char AutoVersion::UBUNTU_VERSION_STYLE[] = '14\&.10'\fC [static]\fP"

.PP
Definition at line 10 of file version\&.h\&.
.SS "const char AutoVersion::YEAR[] = '2014'\fC [static]\fP"

.PP
Definition at line 9 of file version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
