.TH "Body" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Body \- 
.PP
\fBBody\fP component\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.PP
Inherits Component< Body >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBody\fP (b2Body *_body)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Body * \fBbody\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBody\fP component\&. 

The \fBBody\fP component store a pointer to a b2Body and is used to simulate physics in the game world\&. 
.PP
Definition at line 13 of file components\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Body::Body (b2Body *_body)\fC [inline]\fP"

.PP
Definition at line 17 of file components\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "b2Body* Body::body"

.PP
Definition at line 15 of file components\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
