.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/Category.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/Category.h \- 
.PP
Category of entity\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCategory\fP { \fBCategory::None\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Category of entity\&. 

The category is used to dipatch tasks and commands between differents types of entities\&. 
.PP
Definition in file \fBCategory\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCategory\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
Category that correspond to nothing\&. 
.PP
Definition at line 7 of file Category\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
