.TH "html/class_game_state.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/class_game_state.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclass_game_state\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var class_game_state"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "GameState", "class_game_state\&.html#aeb2e2598754640c694b989311b1aebfe", null ],
    [ "draw", "class_game_state\&.html#a3c511417d8934943ae65c04681f321a3", null ],
    [ "handleEvent", "class_game_state\&.html#a000dd3306b1cb9faab5a86774a22aa6d", null ],
    [ "update", "class_game_state\&.html#a4ac988f0da5c33b43ff356890fcf9c1c", null ]
]
.fi
.PP
Definition at line 1 of file class_game_state\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
