.TH "html/class_resource_holder.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/class_resource_holder.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclass_resource_holder\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var class_resource_holder"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "get", "class_resource_holder\&.html#a6452638a75b6df7ea7d610f204632850", null ],
    [ "get", "class_resource_holder\&.html#a9cdb23504de69625ec8405e94a45448f", null ],
    [ "load", "class_resource_holder\&.html#accb6a2b6bd2da503ddfd57b5c0028a16", null ],
    [ "load", "class_resource_holder\&.html#ae83a7a88b2b2a74b6143796eb4452110", null ]
]
.fi
.PP
Definition at line 1 of file class_resource_holder\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
