.TH "html/class_actions.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/class_actions.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclass_actions\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var class_actions"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Actions", "class_actions\&.html#a650c34d9f8890bdd45c94b745cc78c6d", null ],
    [ "update", "class_actions\&.html#a28e5c9bdb7e429a52286fcc549f496b7", null ]
]
.fi
.PP
Definition at line 1 of file class_actions\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
