.TH "html/class_render.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/class_render.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclass_render\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var class_render"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Render", "class_render\&.html#a04b360acbe178ba4a633522f5dea5ba7", null ],
    [ "update", "class_render\&.html#a9b119f3c11007848cf6e38970eb8a946", null ]
]
.fi
.PP
Definition at line 1 of file class_render\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
