.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/Command.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/Command.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <SFML/System/Time\&.hpp>\fP
.br
\fC#include <entityx/entityx\&.h>\fP
.br
\fC#include <TheLostGirl/Category\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCommand\fP"
.br
.RI "\fIFunction applied to an entity\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::queue< \fBCommand\fP > \fBCommandQueue\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::queue<\fBCommand\fP> \fBCommandQueue\fP"

.PP
Definition at line 30 of file Command\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
