.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/components.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/components.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/System\&.hpp>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <entityx/entityx\&.h>\fP
.br
\fC#include <Box2D/Dynamics/b2Body\&.h>\fP
.br
\fC#include <TheLostGirl/Category\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBody\fP"
.br
.RI "\fI\fBBody\fP component\&. \fP"
.ti -1c
.RI "struct \fBSpriteComponent\fP"
.br
.RI "\fISprite component\&. \fP"
.ti -1c
.RI "struct \fBWalk\fP"
.br
.RI "\fI\fBWalk\fP component\&. \fP"
.ti -1c
.RI "struct \fBJump\fP"
.br
.RI "\fI\fBJump\fP component\&. \fP"
.ti -1c
.RI "struct \fBController\fP"
.br
.RI "\fIThe \fBController\fP component\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
