.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/constants.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/constants.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <SFML/System/Vector2\&.hpp>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const sf::Vector2f \fBwindowSize\fP {1024, 576}"
.br
.RI "\fIThe size of the window\&. \fP"
.ti -1c
.RI "const float \fBpixelScale\fP {60}"
.br
.RI "\fIPixel/meter scale\&. Scales : 37\&.5, 60, 75, 93\&.75, 112\&.5\&. \fP"
.ti -1c
.RI "const float \fBg\fP = -1089\&.62777778"
.br
.RI "\fIThe gravity constant, in pixel/second^2\&. \fP"
.ti -1c
.RI "const float \fBpi\fP = 3\&.14159265"
.br
.RI "\fIThe pi constant\&. \fP"
.ti -1c
.RI "const int \fBnumberOfPlans\fP = 4"
.br
.RI "\fINumber of plans in the background\&. \fP"
.ti -1c
.RI "const std::string \fBguiConfig\fP = 'ressources/gui/Black\&.conf'"
.br
.RI "\fIPath of the GUI configuration file\&. \fP"
.ti -1c
.RI "const std::string \fBtextFont\fP = 'ressources/fonts/euphorigenic\&.ttf'"
.br
.RI "\fIPath of the main font\&. \fP"
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const float g = -1089\&.62777778"

.PP
The gravity constant, in pixel/second^2\&. 
.PP
Definition at line 12 of file constants\&.h\&.
.SS "const std::string guiConfig = 'ressources/gui/Black\&.conf'"

.PP
Path of the GUI configuration file\&. 
.PP
Definition at line 15 of file constants\&.h\&.
.SS "const int numberOfPlans = 4"

.PP
Number of plans in the background\&. 
.PP
Definition at line 14 of file constants\&.h\&.
.SS "const float pi = 3\&.14159265"

.PP
The pi constant\&. 
.PP
Definition at line 13 of file constants\&.h\&.
.SS "const float pixelScale {60}"

.PP
Pixel/meter scale\&. Scales : 37\&.5, 60, 75, 93\&.75, 112\&.5\&. 
.PP
Definition at line 11 of file constants\&.h\&.
.SS "const std::string textFont = 'ressources/fonts/euphorigenic\&.ttf'"

.PP
Path of the main font\&. 
.PP
Definition at line 16 of file constants\&.h\&.
.SS "const sf::Vector2f windowSize {1024, 576}"

.PP
The size of the window\&. 
.PP
Definition at line 10 of file constants\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
