.TH "html/constants_8h.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/constants_8h.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBconstants_8h\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var constants_8h"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "g", "constants_8h\&.html#a34a8030233d73a4fbcc839627b28715f", null ],
    [ "guiConfig", "constants_8h\&.html#a2dfc20c88a72462cb06626dfcb89a33f", null ],
    [ "numberOfPlans", "constants_8h\&.html#abbae2b819fd2e4a8eb36314713fcad07", null ],
    [ "pi", "constants_8h\&.html#abce8f0db8a5282e441988c8d2e73f79e", null ],
    [ "pixelScale", "constants_8h\&.html#a209e96bfcaccf20ee3dc68539c4edd0a", null ],
    [ "textFont", "constants_8h\&.html#a60bbb26383e9e449b495a7906094879f", null ],
    [ "windowSize", "constants_8h\&.html#acc6885d86f72ede12978a9140bc735da", null ]
]
.fi
.PP
Definition at line 1 of file constants_8h\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
