.TH "GameState" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameState\&.h>\fP
.PP
Inherits \fBState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameState\fP (\fBStateStack\fP &stack, \fBContext\fP context)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP ()"
.br
.RI "\fIThe drawing function\&. \fP"
.ti -1c
.RI "virtual bool \fBupdate\fP (sf::Time dt)"
.br
.RI "\fIThe logic update function\&. \fP"
.ti -1c
.RI "virtual bool \fBhandleEvent\fP (const sf::Event &event)"
.br
.RI "\fIThe event handling function\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file GameState\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameState::GameState (\fBStateStack\fP &stack, \fBContext\fPcontext)"

.PP
Definition at line 3 of file GameState\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void GameState::draw ()\fC [virtual]\fP"

.PP
The drawing function\&. 
.PP
\fBReturns:\fP
.RS 4
virtual void It must do all things related to drawing stuff on the screen\&. 
.RE
.PP

.PP
Implements \fBState\fP\&.
.PP
Definition at line 13 of file GameState\&.cpp\&.
.SS "bool GameState::handleEvent (const sf::Event &event)\fC [virtual]\fP"

.PP
The event handling function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP Event to handle\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true if the state under this state in the stack must be also updated\&. The state must decide what to do with the event\&. The closing window and resinzing window events are already handled by the \fBApplication\fP class\&. 
.RE
.PP

.PP
Implements \fBState\fP\&.
.PP
Definition at line 22 of file GameState\&.cpp\&.
.SS "bool GameState::update (sf::Timedt)\fC [virtual]\fP"

.PP
The logic update function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdt\fP Elapsed time since the last game frame\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true if the state under this state in the stack must be also updated\&. This function call e\&.g\&. the physic update function, the AI function, etc\&.\&.\&. 
.RE
.PP

.PP
Implements \fBState\fP\&.
.PP
Definition at line 17 of file GameState\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
