.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/GameState.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/GameState.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics/Sprite\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Text\&.hpp>\fP
.br
\fC#include <SFML/Graphics/RenderWindow\&.hpp>\fP
.br
\fC#include <SFML/Graphics/View\&.hpp>\fP
.br
\fC#include <entityx/entityx\&.h>\fP
.br
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <TheLostGirl/State\&.h>\fP
.br
\fC#include <TheLostGirl/functions\&.h>\fP
.br
\fC#include <TheLostGirl/Player\&.h>\fP
.br
\fC#include <TheLostGirl/Command\&.h>\fP
.br
\fC#include <TheLostGirl/ResourceManager\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
