.TH "Jump" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Jump \- 
.PP
\fBJump\fP component\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.PP
Inherits Component< Jump >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJump\fP (float _jumpStrength)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBjumpStrength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJump\fP component\&. 

The \fBJump\fP component must be added to every entity that want to jump\&. The jumpStrength member influences directly the height of the jump of the entity\&. 
.PP
Definition at line 47 of file components\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Jump::Jump (float_jumpStrength)\fC [inline]\fP"

.PP
Definition at line 50 of file components\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Jump::jumpStrength"

.PP
Definition at line 49 of file components\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
