.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/LangManager.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/LangManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <locale>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLangManager\fP"
.br
.RI "\fILanguage manager that translate strings\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLang\fP { \fBEN\fP, \fBFR\fP, \fBNL\fP, \fBIT\fP }"
.br
.RI "\fIAvailable langages\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLang\fP"

.PP
Available langages\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEN \fP\fP
The English\&. 
.TP
\fB\fIFR \fP\fP
The French\&. 
.TP
\fB\fINL \fP\fP
The Dutch\&. 
.TP
\fB\fIIT \fP\fP
The Italian\&. 
.PP
Definition at line 11 of file LangManager\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
