.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/MainMenuState.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/MainMenuState.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <TGUI/TGUI\&.hpp>\fP
.br
\fC#include <TheLostGirl/State\&.h>\fP
.br
\fC#include <TheLostGirl/LangManager\&.h>\fP
.br
\fC#include <TheLostGirl/constants\&.h>\fP
.br
\fC#include <TheLostGirl/functions\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainMenuState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
