.TH "html/navtree.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/navtree.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBgetData\fP (varName)"
.br
.ti -1c
.RI "function \fBstripPath\fP (uri)"
.br
.ti -1c
.RI "function \fBstripPath2\fP (uri)"
.br
.ti -1c
.RI "function \fBlocalStorageSupported\fP ()"
.br
.ti -1c
.RI "function \fBstoreLink\fP (link)"
.br
.ti -1c
.RI "function \fBdeleteLink\fP ()"
.br
.ti -1c
.RI "function \fBcachedLink\fP ()"
.br
.ti -1c
.RI "function \fBgetScript\fP (scriptName, func, show)"
.br
.ti -1c
.RI "function \fBcreateIndent\fP (o, domNode, node, level)"
.br
.ti -1c
.RI "function \fBgotoAnchor\fP (anchor, aname, updateLocation)"
.br
.ti -1c
.RI "function \fBnewNode\fP (o, po, text, link, childrenData, lastNode)"
.br
.ti -1c
.RI "function \fBshowRoot\fP ()"
.br
.ti -1c
.RI "function \fBexpandNode\fP (o, node, imm, \fBshowRoot\fP)"
.br
.ti -1c
.RI "function \fBglowEffect\fP (n, duration)"
.br
.ti -1c
.RI "function \fBhighlightAnchor\fP ()"
.br
.ti -1c
.RI "function \fBselectAndHighlight\fP (hash, n)"
.br
.ti -1c
.RI "function \fBshowNode\fP (o, node, index, hash)"
.br
.ti -1c
.RI "function \fBremoveToInsertLater\fP (element)"
.br
.ti -1c
.RI "function \fBgetNode\fP (o, po)"
.br
.ti -1c
.RI "function \fBgotoNode\fP (o, subIndex, root, hash, relpath)"
.br
.ti -1c
.RI "function \fBnavTo\fP (o, root, hash, relpath)"
.br
.ti -1c
.RI "function \fBshowSyncOff\fP (n, relpath)"
.br
.ti -1c
.RI "function \fBshowSyncOn\fP (n, relpath)"
.br
.ti -1c
.RI "function \fBtoggleSyncButton\fP (relpath)"
.br
.ti -1c
.RI "function \fBinitNavTree\fP (toroot, relpath)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBNAVTREE\fP"
.br
.ti -1c
.RI "var \fBNAVTREEINDEX\fP"
.br
.ti -1c
.RI "var \fBSYNCONMSG\fP = 'click to disable panel synchronisation'"
.br
.ti -1c
.RI "var \fBSYNCOFFMSG\fP = 'click to enable panel synchronisation'"
.br
.ti -1c
.RI "var \fBnavTreeSubIndices\fP = new Array()"
.br
.ti -1c
.RI "var \fBanimationInProgress\fP = false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function cachedLink ()"

.PP
Definition at line 85 of file navtree\&.js\&.
.SS "function createIndent (o, domNode, node, level)"

.PP
Definition at line 113 of file navtree\&.js\&.
.SS "function deleteLink ()"

.PP
Definition at line 78 of file navtree\&.js\&.
.SS "function expandNode (o, node, imm, showRoot)"

.PP
Definition at line 273 of file navtree\&.js\&.
.SS "function getData (varName)"

.PP
Definition at line 40 of file navtree\&.js\&.
.SS "function getNode (o, po)"

.PP
Definition at line 409 of file navtree\&.js\&.
.SS "function getScript (scriptName, func, show)"

.PP
Definition at line 94 of file navtree\&.js\&.
.SS "function glowEffect (n, duration)"

.PP
Definition at line 301 of file navtree\&.js\&.
.SS "function gotoAnchor (anchor, aname, updateLocation)"

.PP
Definition at line 151 of file navtree\&.js\&.
.SS "function gotoNode (o, subIndex, root, hash, relpath)"

.PP
Definition at line 422 of file navtree\&.js\&.
.SS "function highlightAnchor ()"

.PP
Definition at line 308 of file navtree\&.js\&.
.SS "function initNavTree (toroot, relpath)"

.PP
Definition at line 492 of file navtree\&.js\&.
.SS "function localStorageSupported ()"

.PP
Definition at line 60 of file navtree\&.js\&.
.SS "function navTo (o, root, hash, relpath)"

.PP
Definition at line 437 of file navtree\&.js\&.
.SS "function newNode (o, po, text, link, childrenData, lastNode)"

.PP
Definition at line 177 of file navtree\&.js\&.
.SS "function removeToInsertLater (element)"

.PP
Definition at line 396 of file navtree\&.js\&.
.SS "function selectAndHighlight (hash, n)"

.PP
Definition at line 328 of file navtree\&.js\&.
.SS "function showNode (o, node, index, hash)"

.PP
Definition at line 351 of file navtree\&.js\&.
.SS "function showRoot ()"

.PP
Definition at line 258 of file navtree\&.js\&.
.SS "function showSyncOff (n, relpath)"

.PP
Definition at line 468 of file navtree\&.js\&.
.SS "function showSyncOn (n, relpath)"

.PP
Definition at line 473 of file navtree\&.js\&.
.SS "function storeLink (link)"

.PP
Definition at line 71 of file navtree\&.js\&.
.SS "function stripPath (uri)"

.PP
Definition at line 47 of file navtree\&.js\&.
.SS "function stripPath2 (uri)"

.PP
Definition at line 52 of file navtree\&.js\&.
.SS "function toggleSyncButton (relpath)"

.PP
Definition at line 478 of file navtree\&.js\&.
.SH "Variable Documentation"
.PP 
.SS "var animationInProgress = false"

.PP
Definition at line 149 of file navtree\&.js\&.
.SS "var NAVTREE"
\fBInitial value:\fP
.PP
.nf
=
[
  [ "The Lost Girl", "index\&.html", [
    [ "Classes", null, [
      [ "Class List", "annotated\&.html", "annotated" ],
      [ "Class Hierarchy", "hierarchy\&.html", "hierarchy" ],
      [ "Class Members", "functions\&.html", [
        [ "All", "functions\&.html", null ],
        [ "Functions", "functions_func\&.html", null ],
        [ "Variables", "functions_vars\&.html", null ],
        [ "Typedefs", "functions_type\&.html", null ],
        [ "Enumerations", "functions_enum\&.html", null ],
        [ "Enumerator", "functions_eval\&.html", null ]
      ] ]
    ] ],
    [ "Files", null, [
      [ "File List", "files\&.html", "files" ],
      [ "File Members", "globals\&.html", [
        [ "All", "globals\&.html", null ],
        [ "Functions", "globals_func\&.html", null ],
        [ "Variables", "globals_vars\&.html", null ],
        [ "Enumerations", "globals_enum\&.html", null ],
        [ "Enumerator", "globals_eval\&.html", null ]
      ] ]
    ] ]
  ] ]
]
.fi
.PP
Definition at line 1 of file navtree\&.js\&.
.SS "var NAVTREEINDEX"
\fBInitial value:\fP
.PP
.nf
=
[
"_application_8h_source\&.html"
]
.fi
.PP
Definition at line 29 of file navtree\&.js\&.
.SS "var navTreeSubIndices = new Array()"

.PP
Definition at line 38 of file navtree\&.js\&.
.SS "var SYNCOFFMSG = 'click to enable panel synchronisation'"

.PP
Definition at line 35 of file navtree\&.js\&.
.SS "var SYNCONMSG = 'click to disable panel synchronisation'"

.PP
Definition at line 34 of file navtree\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
