.TH "Render" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Render \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <systems\&.h>\fP
.PP
Inherits System< Render >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRender\fP (sf::RenderWindow &\fBwindow\fP)"
.br
.ti -1c
.RI "void \fBupdate\fP (entityx::EntityManager &es, entityx::EventManager &events, double dt) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file systems\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Render::Render (sf::RenderWindow &window)\fC [inline]\fP"

.PP
Definition at line 32 of file systems\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Render::update (entityx::EntityManager &es, entityx::EventManager &events, doubledt)\fC [override]\fP"

.PP
Definition at line 24 of file systems\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
