.TH "ResourceManager< Resource, Identifier >" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceManager< Resource, Identifier > \- 
.PP
Simple ressource manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceIdentifiers\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBload\fP (Identifier id, const std::string &filename)"
.br
.RI "\fILoad the ressource identified by \fIid\fP at the path \fIfilename\fP in the memory\&. \fP"
.ti -1c
.RI "template<typename Parameter > void \fBload\fP (Identifier id, const std::string &filename, const Parameter &secondParam)"
.br
.RI "\fIOverloaded function that pass a custom argument to the SFML's loading function\&. \fP"
.ti -1c
.RI "Resource & \fBget\fP (Identifier id)"
.br
.RI "\fIGet the ressource identified by id\&. \fP"
.ti -1c
.RI "const Resource & \fBget\fP (Identifier id) const "
.br
.RI "\fIConst overload of the get function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Resource, typename Identifier>class ResourceManager< Resource, Identifier >"
Simple ressource manager\&. 

It loads and holds many type of SFML's ressources and restitues them To do not have to load them many times\&. 
.PP
Definition at line 21 of file ResourceIdentifiers\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Resource , typename Identifier> Resource & \fBResourceManager\fP< Resource, Identifier >::get (Identifierid)"

.PP
Get the ressource identified by id\&. This function can be called only if the ressource was loaded before by the load function\&. If the ressource was not yet loaded, an assertion is raised\&. So in Release mode it is your responsability to handle right the ressources\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identifier of the ressource to get\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Reference to the ressource\&. 
.RE
.PP

.PP
Definition at line 29 of file ResourceManager\&.inl\&.
.SS "template<typename Resource , typename Identifier> const Resource & \fBResourceManager\fP< Resource, Identifier >::get (Identifierid) const"

.PP
Const overload of the get function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identifier of the ressource to get\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Const reference to the ressource\&. 
.RE
.PP

.PP
Definition at line 37 of file ResourceManager\&.inl\&.
.SS "template<typename Resource , typename Identifier> void \fBResourceManager\fP< Resource, Identifier >::load (Identifierid, const std::string &filename)"

.PP
Load the ressource identified by \fIid\fP at the path \fIfilename\fP in the memory\&. Once you loaded the ressource, you can then get it simply with the function \fIget\fP, so the ressource is loaded only one time\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identifier of the ressource, defined in RessourceIdentifiers\&.h 
.br
\fIfilename\fP String of the path to the ressource\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 2 of file ResourceManager\&.inl\&.
.SS "template<typename Resource , typename Identifier> template<typename Parameter > void \fBResourceManager\fP< Resource, Identifier >::load (Identifierid, const std::string &filename, const Parameter &secondParam)"

.PP
Overloaded function that pass a custom argument to the SFML's loading function\&. It is useful to load only a certain part of a texture, a type of shader, \&.\&.\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identifier of the ressource, defined in RessourceIdentifiers\&.h 
.br
\fIfilename\fP String of the path to the ressource\&. 
.br
\fIsecondParam\fP Additional parameter, it can be every type you want, and is passed to the SFML's loading function\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 16 of file ResourceManager\&.inl\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
