.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/ResourceManager.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/ResourceManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <TheLostGirl/ResourceManager\&.inl>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResourceManager< Resource, Identifier >\fP"
.br
.RI "\fISimple ressource manager\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
