.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/ResourceIdentifiers.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/ResourceIdentifiers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResourceManager< Resource, Identifier >\fP"
.br
.RI "\fISimple ressource manager\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBResourceManager\fP
.br
< sf::Texture, \fBTextures\fP > \fBTextureManager\fP"
.br
.RI "\fITypedef of RessourceManager\&. \fP"
.ti -1c
.RI "typedef \fBResourceManager\fP
.br
< sf::Font, \fBFonts\fP > \fBFontManager\fP"
.br
.RI "\fITypedef of RessourceManager\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTextures\fP { \fBTextures::Archer\fP }"
.br
.RI "\fIList all the texutres\&. \fP"
.ti -1c
.RI "enum \fBFonts\fP { \fBFonts::Menu\fP }"
.br
.RI "\fIList of all fonts\&. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBResourceManager\fP<sf::Font, \fBFonts\fP> \fBFontManager\fP"

.PP
Typedef of RessourceManager\&. 
.PP
Definition at line 26 of file ResourceIdentifiers\&.h\&.
.SS "typedef \fBResourceManager\fP<sf::Texture, \fBTextures\fP> \fBTextureManager\fP"

.PP
Typedef of RessourceManager\&. 
.PP
Definition at line 21 of file ResourceIdentifiers\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFonts\fP\fC [strong]\fP"

.PP
List of all fonts\&. This enum is used with a FontManager\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMenu \fP\fP
The GUI font\&. 
.PP
Definition at line 15 of file ResourceIdentifiers\&.h\&.
.SS "enum \fBTextures\fP\fC [strong]\fP"

.PP
List all the texutres\&. This enum is used with a TextureManager\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIArcher \fP\fP
The texture of the main archer\&. 
.PP
Definition at line 8 of file ResourceIdentifiers\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
