.TH "SpriteComponent" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteComponent \- 
.PP
Sprite component\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.PP
Inherits Component< SpriteComponent >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpriteComponent\fP (const sf::Sprite &_sprite)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sf::Sprite \fBsprite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sprite component\&. 

The Sprite component is an essential component for any visible entity\&. For more information about sprites, see the SFML doc\&. 
.PP
Definition at line 25 of file components\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpriteComponent::SpriteComponent (const sf::Sprite &_sprite)\fC [inline]\fP"

.PP
Definition at line 28 of file components\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "sf::Sprite SpriteComponent::sprite"

.PP
Definition at line 27 of file components\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
