.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/StateIdentifiers.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/StateIdentifiers.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStates\fP { \fBStates::None\fP, \fBStates::MainMenu\fP, \fBStates::Loading\fP, \fBStates::Intro\fP, \fBStates::Game\fP, \fBStates::Pause\fP }"
.br
.RI "\fIThe various game states\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBStates\fP\fC [strong]\fP"

.PP
The various game states\&. Every \fBState\fP class correspond to a \fBState\fP identifiers here\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
No state\&. 
.TP
\fB\fIMainMenu \fP\fP
The MAin menu state, from where you can start the game\&. 
.TP
\fB\fILoading \fP\fP
The state where the level is loaded\&. 
.TP
\fB\fIIntro \fP\fP
The intro state\&. 
.TP
\fB\fIGame \fP\fP
The main gamepay state\&. 
.TP
\fB\fIPause \fP\fP
.PP
Definition at line 6 of file StateIdentifiers\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
