.TH "StateStack" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StateStack \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateStack\&.h>\fP
.PP
Inherits NonCopyable\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAction\fP { \fBPush\fP, \fBPop\fP, \fBClear\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateStack\fP (\fBState::Context\fP context)"
.br
.ti -1c
.RI "template<typename T > void \fBregisterState\fP (\fBStates\fP stateID)"
.br
.ti -1c
.RI "void \fBupdate\fP (sf::Time dt)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBhandleEvent\fP (const sf::Event &event)"
.br
.ti -1c
.RI "void \fBpushState\fP (\fBStates\fP stateID)"
.br
.ti -1c
.RI "void \fBpopState\fP ()"
.br
.ti -1c
.RI "void \fBclearStates\fP ()"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file StateStack\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBStateStack::Action\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPush \fP\fP
.TP
\fB\fIPop \fP\fP
.TP
\fB\fIClear \fP\fP
.PP
Definition at line 28 of file StateStack\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StateStack::StateStack (\fBState::Context\fPcontext)\fC [explicit]\fP"

.PP
Definition at line 3 of file StateStack\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void StateStack::clearStates ()"

.PP
Definition at line 52 of file StateStack\&.cpp\&.
.SS "void StateStack::draw ()"

.PP
Definition at line 23 of file StateStack\&.cpp\&.
.SS "void StateStack::handleEvent (const sf::Event &event)"

.PP
Definition at line 30 of file StateStack\&.cpp\&.
.SS "bool StateStack::isEmpty () const"

.PP
Definition at line 57 of file StateStack\&.cpp\&.
.SS "void StateStack::popState ()"

.PP
Definition at line 47 of file StateStack\&.cpp\&.
.SS "void StateStack::pushState (\fBStates\fPstateID)"

.PP
Definition at line 42 of file StateStack\&.cpp\&.
.SS "template<typename T > void StateStack::registerState (\fBStates\fPstateID)"

.PP
Definition at line 61 of file StateStack\&.h\&.
.SS "void StateStack::update (sf::Timedt)"

.PP
Definition at line 11 of file StateStack\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
