.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/State.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/State.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <SFML/System/Time\&.hpp>\fP
.br
\fC#include <SFML/Window/Event\&.hpp>\fP
.br
\fC#include <TGUI/TGUI\&.hpp>\fP
.br
\fC#include <entityx/entityx\&.h>\fP
.br
\fC#include <TheLostGirl/StateIdentifiers\&.h>\fP
.br
\fC#include <TheLostGirl/ResourceIdentifiers\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState\fP"
.br
.RI "\fIBase class for the various game states\&. \fP"
.ti -1c
.RI "struct \fBState::Context\fP"
.br
.RI "\fIVarious managers and globals instances\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBsf\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
