.TH "html/struct_controller.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/struct_controller.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBstruct_controller\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var struct_controller"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Controller", "struct_controller\&.html#a865447d116f208f376b62c5e1f773c23", null ],
    [ "isPlayer", "struct_controller\&.html#a63ef3bfeb160883be0dbd7e70a8e340d", null ]
]
.fi
.PP
Definition at line 1 of file struct_controller\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
