.TH "html/struct_jump.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/struct_jump.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBstruct_jump\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var struct_jump"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Jump", "struct_jump\&.html#aab33624b76fd15b361529375c50b0f5a", null ],
    [ "jumpStrength", "struct_jump\&.html#a5a465cb45b656e6290d7da0d1f1a75f3", null ]
]
.fi
.PP
Definition at line 1 of file struct_jump\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
