.TH "html/struct_sprite_component.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/struct_sprite_component.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBstruct_sprite_component\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var struct_sprite_component"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "SpriteComponent", "struct_sprite_component\&.html#a80feb843c0634da98657ca77a9651407", null ],
    [ "sprite", "struct_sprite_component\&.html#ac49ac20d7050d549b853b97c43790164", null ]
]
.fi
.PP
Definition at line 1 of file struct_sprite_component\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
