.TH "html/struct_body.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/struct_body.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBstruct_body\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var struct_body"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Body", "struct_body\&.html#ae2ed3ebb89b25b28ad53a64f4f00289c", null ],
    [ "body", "struct_body\&.html#adfe45f07e6da7eb54f4cc93eef03f8c6", null ]
]
.fi
.PP
Definition at line 1 of file struct_body\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
