.TH "/home/theo/C++/TheLostGirl-0.0.8/src/systems.cpp" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/src/systems.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <TheLostGirl/systems\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
