.TH "/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/systems.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/include/TheLostGirl/systems.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <SFML/System\&.hpp>\fP
.br
\fC#include <SFML/Window\&.hpp>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <entityx/entityx\&.h>\fP
.br
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <TheLostGirl/components\&.h>\fP
.br
\fC#include <TheLostGirl/constants\&.h>\fP
.br
\fC#include <TheLostGirl/Command\&.h>\fP
.br
\fC#include <TheLostGirl/Player\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActions\fP"
.br
.ti -1c
.RI "class \fBRender\fP"
.br
.ti -1c
.RI "class \fBPhysics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
