.TH "html/search/typedefs_0.js" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/typedefs_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['ptr',['Ptr',['\&.\&./class_state\&.html#a71d9930be1a58be7f711e245b7965d48',1,'State']]]
]
.fi
.PP
Definition at line 1 of file typedefs_0\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
