.TH "/home/theo/C++/TheLostGirl-0.0.8/version.h" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/theo/C++/TheLostGirl-0.0.8/version.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBAutoVersion\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRC_FILEVERSION\fP   0,0,7,0"
.br
.ti -1c
.RI "#define \fBRC_FILEVERSION_STRING\fP   '0, 0, 7, 0\\0'"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBAutoVersion::DATE\fP [] = '01'"
.br
.ti -1c
.RI "static const char \fBAutoVersion::MONTH\fP [] = '10'"
.br
.ti -1c
.RI "static const char \fBAutoVersion::YEAR\fP [] = '2014'"
.br
.ti -1c
.RI "static const char \fBAutoVersion::UBUNTU_VERSION_STYLE\fP [] = '14\&.10'"
.br
.ti -1c
.RI "static const char \fBAutoVersion::STATUS\fP [] = 'Prealpha'"
.br
.ti -1c
.RI "static const char \fBAutoVersion::STATUS_SHORT\fP [] = 'pa'"
.br
.ti -1c
.RI "static const long \fBAutoVersion::MAJOR\fP = 0"
.br
.ti -1c
.RI "static const long \fBAutoVersion::MINOR\fP = 0"
.br
.ti -1c
.RI "static const long \fBAutoVersion::BUILD\fP = 7"
.br
.ti -1c
.RI "static const long \fBAutoVersion::REVISION\fP = 0"
.br
.ti -1c
.RI "static const long \fBAutoVersion::BUILDS_COUNT\fP = 1"
.br
.ti -1c
.RI "static const char \fBAutoVersion::FULLVERSION_STRING\fP [] = '0\&.0\&.7\&.0'"
.br
.ti -1c
.RI "static const long \fBAutoVersion::BUILD_HISTORY\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RC_FILEVERSION   0,0,7,0"

.PP
Definition at line 24 of file version\&.h\&.
.SS "#define RC_FILEVERSION_STRING   '0, 0, 7, 0\\0'"

.PP
Definition at line 25 of file version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
