.TH "Walk" 3 "Wed Oct 8 2014" "Version 0.0.8 prealpha" "The Lost Girl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Walk \- 
.PP
\fBWalk\fP component\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.PP
Inherits Component< Walk >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWalk\fP (float _walkSpeed)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBwalkSpeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWalk\fP component\&. 

The walk component must be added to every entity that want to move itself in the world\&. The walkSpeed member is the maximum speed that the entity can reach when walking\&. 
.PP
Definition at line 36 of file components\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Walk::Walk (float_walkSpeed)\fC [inline]\fP"

.PP
Definition at line 39 of file components\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Walk::walkSpeed"

.PP
Definition at line 38 of file components\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Lost Girl from the source code\&.
